"""Add profile_image to users and create students table

Revision ID: 581f016f260d
Revises: 003_add_registered_date
Create Date: 2025-11-05 22:30:39.957376

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "581f016f260d"
down_revision: Union[str, Sequence[str], None] = "003_add_registered_date"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("profile_image", sa.LargeBinary(), nullable=True))
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.alter_column(
        "users",
        "is_approved",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "is_rejected",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "registered_date",
        existing_type=postgresql.TIMESTAMP(),
        comment=None,
        existing_comment="UTC datetime when user was registered/approved by admin",
        existing_nullable=True,
    )
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.create_unique_constraint(
        op.f("uq_users_username"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column(
        "users",
        "registered_date",
        existing_type=postgresql.TIMESTAMP(),
        comment="UTC datetime when user was registered/approved by admin",
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "is_rejected",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "is_approved",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column(
        "users",
        "role",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_server_default=sa.text("'pending'::character varying"),
    )
    op.drop_column("users", "profile_image")
    # ### end Alembic commands ###
